version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=username
      - PASS=password
      - COUNTRY=United_States
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      - TZ=America/Denver
    restart: unless-stopped
